#!/bin/bash
# (wall)pa(per) changer

##defaults
# folder for wallpapers
f=~/.local/share/pa/
# program for wallpapers
p='xwallpaper '
# options for wallpapers
o='--zoom'
# built in theme for background "bg"
d='--theme base16-gruvbox-hard'
# wal options
wo='-q -n -i'

# TODO
# Make the args properly, especially -o and -w

if test "$#" -eq 0
then
	#bg is default background
	#$p$o $fbg # uncomment this if you want a normal bg
	$p --center $f"bg"
	#This is to immediately change the colors
	wal -q -n $d
	#This is to restore them to true defaults
	xrdb ~/.config/x11/xresources
	exit
fi


if ! [[ $1 = -* ]]
then
	$p $o $f$1
	exit
fi

for arg in "$@"
do
	case $arg in
		-l|--list)
		ls $f
		exit
		;;
		-a|--add)
		shift
		cp $@ -t $f
		exit
		;;
		-r|--remove)
		shift
		rm $f$@
		exit
		;;
		-c|--copy)
		shift
		cp $f$@ . # If you want to copy all, give * as "*"
		exit
		;;
		-m|--move)
		shift
		mv $f$1 $f$2
		exit
		;;
		-o|--option)
		shift
		o=$1
		shift
		#$p$2 $f$3
		;;
		-w|--wal)
		shift
		w=true
		;;
		-wo|--wallopts)
		shift
		wo=$1
		shift
		;;
#		-cd|--changedir)
#		sed "s/f=.*/$2" pa
#		exit 0
#		;;
		-d|--directory)
		echo $f
		exit
		;;
		-s|--show)
		if "$w" = true
		then
			for file in $(ls $f)
			do
				$p $o $f$file
				wal $wo $f$file
				read
			done
			exit
		fi

		for file in $(ls $f)
		do
			$p $o $f$file
			read
		done

		exit
		;;
		-ll|--loop)
		shift

		if "$w" = true
		then
			while :
			do
				for file in $(ls $f)
				do
					$p $o $f$file
					wal $wo $f$file
					sleep ${1-20}
				done
			done
			exit
		fi

		while :
		do
			for file in $(ls $f)
			do
				$p $o $f$file
				sleep ${1-20}
			done
		done

		exit
		;;
		-se|--see)
		sxiv $f${2-*}
		exit
		;;
#		--init)
#		chmod +x ./pa
#		mv -f ./pa ~/.local/bin
#		mkdir ~/.local/share/pa
#		exit
#		;;
	esac
done

$p $o $f$1

if test "$w" = true
then
	wal $wo $f$1
fi
