#!/bin/bash
# (wall)pa(per) changer

##defaults
# folder for wallpapers
f=~/.local/share/pa/
# program for wallpapers
p='xwallpaper'
# options for wallpapers
o='--zoom'
# built in theme for background "bg"
d='--theme base16-gruvbox-hard'
# wal options
wo='-q -n -i'

if test "$#" -eq 0
then
	#bg is default background
	$p --center $f"../bg"
	#Set colors to default
	xrdb ~/.config/x11/xresources ;
	kill -HUP $(pgrep -u $USER "\bdwm$")
	exit
fi


if ! [[ $1 = -* ]]
then
	$p $o $f$1
	exit
fi

for arg in "$@"
do
	case $arg in
		-l|--list)
		ls $f
		exit
		;;
		-a|--add)
		shift
		cp -r $@ -t $f
		exit
		;;
		-r|--remove)
		shift
		rm $f$@
		exit
		;;
		-c|--copy)
		shift
		cp $f$@ . # If you want to copy all, give * as "*"
		exit
		;;
		-m|--move)
		shift
		mv $f$1 $f$2
		exit
		;;
		-o|--option)
		shift
		o=$1
		shift
		;;
		-w|--wal)
		shift
		w=true
		;;
		-wo|--wallopts)
		shift
		wo=$1
		shift
		;;
		-d|--directory)
		echo $f
		exit
		;;
		# This runs the script in the folder
		-s|--script)
		shift
		cat $f/scripts | grep $1 | sh
		exit
		;;
		-cs|--change-scripts)
		shift
		echo $f/scripts
		exit
		;;
		# -s|--show)
		# if "$w" = true
		# then
		# 	for file in $(ls $f)
		# 	do
		# 		$p $o $f$file
		# 		wal $wo $f$file
		# 		read
		# 	done
		# 	exit
		# fi

		# for file in $(ls $f)
		# do
		# 	$p $o $f$file
		# 	read
		# done

		# exit
		# ;;
		-ll|--loop)
		shift

		if "$w" = true
		then
			while :
			do
				for file in $(ls $f)
				do
					$p $o $f$file
					wal $wo $f$file
					sleep ${1-20}
				done
			done
			exit
		fi

		while :
		do
			for file in $(ls $f)
			do
				$p $o $f$file
				sleep ${1-20}
			done
		done

		exit
		;;
		-se|--see)
		sxiv $f${2-*}
		exit
		;;
		--init)
		chmod +x pa
		cp -f pa ~/.local/bin
		mkdir ~/.local/share/pa
		exit
		;;
	esac
done

$p $o $f$1

if test "$w" = true
then
	wal $wo $f$1
	kill -HUP $(pgrep -u $USER "\bdwm$")
fi
